language: node_js
node_js: 12

script:
  - npm run test-all
  - npm run build
  - npm run export
  - touch out/.nojekyll

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out
  on:
    branch: master
